default:
   - debug: true
     open: bin/video_player.swf
     extra: -default-size 1000 500 -default-background-color 0xFFFFFF -default-frame-rate=30 -target-player=10.0.0 -use-network=false -verbose-stacktraces=true -warn-no-type-decl=true -show-actionscript-warnings=true -strict=true

library-path:
    - lib
    - ../../external-libs

source-path:
   - src
   - ../../src

applications:
   - class: src/Main.as
     output: bin/video_player.swf
