default:
   - debug: true
     open: bin/main.swf
     extra: -use-network=false -verbose-stacktraces=false -warn-no-type-decl=false -show-actionscript-warnings=false -strict=true

library-path:
    - ../../src/saci/uicomponents/videoPlayer/videoPlayerAssets/videoPlayerAssets.swc
    - ../../external-libs/caurina.tweener.swc
    - ../../external-libs/redneck.swc

source-path:
   - src
   - ../../src

applications:
   - class: src/Main.as
     output: bin/main.swf
